# USER ERROR_CODES
USER_ALREADY_EXISTS_ERROR_CODE = "USER_ALREADY_EXISTS"
USER_ALREADY_ACTIVATED_ERROR_CODE = "USER_ALREADY_ACTIVATED"
INVALID_ACTIVATION_CODE_ERROR_CODE = "INVALID_ACTIVATION_CODE"
EXPIRED_ACTIVATION_CODE_ERROR_CODE = "EXPIRED_ACTIVATION_CODE"

# GENERIC ERROR_CODES
VALIDATION_ERROR_CODE = "VALIDATION_ERROR"
INVALID_PASSWORD_ERROR_CODE = "INVALID_PASSWORD"
INVALID_EMAIL_ERROR_CODE = "INVALID_EMAIL"

# USER STATUS
USER_STATUS_CREATED = "created"
USER_STATUS_ACTIVATED = "activated"
